### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by vala-shinshu** [BlueObelisk/cmlxom#14]
I have installed cmlxom using maven and cmd in windows 11 succesfully. Which command should I use to run the program? If I use java -jar ... it says that there is no manifest attribute. Thank you!

**Comment by egonw** [comment]
> I have installed cmlxom using maven and cmd in windows 11 succesfully. Which command should I use to run the program? If I use java -jar ... it says that there is no manifest attribute. Thank you!

I had not received an alert about this message. CMLXOM is not a command line utility, but primarily a Java library. This library is used in various other tools, like the Chemistry Development Kit and OSCAR4.

How do you want to use this library?
